
services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-0.6.5}
    volumes:
      - /opt/open-webui:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_KEY:-default}
      - API_BASE_URL=http://nim-llm-ms:8000/v1
      - ENABLE_OLLAMA_API=true
      - GLOBAL_LOG_LEVEL=INFO
      - VECTOR_DB=milvus
      - MILVUS_URI=http://milvus-standalone:19530
      - MILVUS_DB=default
      - ENABLE_SIGNUP=true
      # Ollama osoite!
  
networks:
  default:
    external: true
    name: nvidia-rag